name: MP Backend CI

on:
  # This is for running on-demand
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      # This will run on changes to the backend code only
      - "starter/backend/**"

env:
  PYTHON_VERSION: 3.10.15

jobs:
  LINT:
    uses: ./.github/workflows/backtend-lint.yaml

  TEST:
    uses: ./.github/workflows/backtend-test.yaml
          
  BUILD:
    name: BUILD JOB
    runs-on: ubuntu-latest
    needs: [LINT, TEST]
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.10.15
      - name: Perform a cache action to restore cache before dependency install
        uses: actions/cache@v4.1.1
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: ${{ runner.os }}-pipenv-
      - name: Install pipenv
        run: pip install pipenv && pip install flake8
      - name: Install dependencies
        run: pipenv install
      - name: Run lint
        run: pipenv run lint
      - name: Build docker image
        run: |
          docker build -t docker/$backend:latest .
          docker images
