name: MP Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      # This will only run on changes to the frontend code
      - "starter/frontend/**"
  # This is for running on-demand
  workflow_dispatch:

jobs:
  LINT:
    steps:
      - name: Use actions
        uses: uses: ./.github/actions/frontend
      - name: Run the npm run lint command
        run: npm run lint -- --fix

  TEST:
    steps:
      - name: Use actions
        uses: uses: ./.github/actions/frontend
      - name: Run the npm run test command
        run: npm run test
    
  BUILD:
    name: BUILD JOB
    runs-on: ubuntu-latest
    needs: [LINT, TEST]
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Use actions
        uses: uses: ./.github/actions/frontend
      - name: Run the npm run test command
        run: npm run test
      - name: Builds the application using docker
        run: |
          docker build -t docker/frontend:latest --build-arg=REACT_APP_MOVIE_API_URL=http://localhost .
          docker images
