name: MP Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      # This will only run on changes to the frontend code
      - "starter/frontend/**"
  # This is for running on-demand
  workflow_dispatch:

jobs:
  LINT:
    uses: ./.github/workflows/frontend-lint.yaml

  TEST:
    uses: ./.github/workflows/frontend-test.yaml
    
  BUILD:
    runs-on: ubuntu-latest
    needs: [LINT, TEST]
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Setup NodeJS / Install dependencies
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.x
      - name: Perform a cache action to restore cache before dependency install
        uses: actions/cache@v4.1.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Run the npm run test command
        run: npm run test
      - name: Builds the application using docker
        run: |
          docker build -t docker/frontend:latest --build-arg=REACT_APP_MOVIE_API_URL=http://localhost .
          docker images
